/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.1 		*/
/*  Created On : 04-ago-2025 4:23:20 p.m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Addresses` CASCADE
;

DROP TABLE IF EXISTS `Artwork` CASCADE
;

DROP TABLE IF EXISTS `Customers` CASCADE
;

DROP TABLE IF EXISTS `Image` CASCADE
;

DROP TABLE IF EXISTS `Job` CASCADE
;

DROP TABLE IF EXISTS `Jobs` CASCADE
;

DROP TABLE IF EXISTS `Orders` CASCADE
;

DROP TABLE IF EXISTS `Text` CASCADE
;

/* Create Tables */

CREATE TABLE `Addresses`
(
	`id_adddress` INT NULL,
	`first_name` VARCHAR(50) NULL,
	`last_name` VARCHAR(50) NULL,
	`company_name` VARCHAR(50) NULL,
	`phone` VARCHAR(50) NULL,
	`country` VARCHAR(50) NULL,
	`state` VARCHAR(50) NULL,
	`town_city` VARCHAR(50) NULL,
	`street_address_1` VARCHAR(200) NULL,
	`street_address_2` VARCHAR(200) NULL,
	`postcode` VARCHAR(50) NULL,
	`email_address` VARCHAR(50) NULL,
	`id_customer` INT NULL,
	`id_customers` INT NULL
)

;

CREATE TABLE `Artwork`
(
	`id_jobs` INT NULL,
	`link_right_image` TEXT NULL,
	`link_left_image` TEXT NULL
)

;

CREATE TABLE `Customers`
(
	`id_customers` INT NOT NULL,
	`name` VARCHAR(50) NULL,
	`email` VARCHAR(50) NULL,
	CONSTRAINT `PK_Users` PRIMARY KEY (`id_customers` ASC)
)

;

CREATE TABLE `Image`
(
	`id_jobs` INT NULL,
	`times_image` INT NULL,
	`image_size` FLOAT(8,2) NULL,
	`space_between_image` FLOAT(8,2) NULL,
	`image_rotation` FLOAT(8,2) NULL,
	`space_along_lanyard` FLOAT(8,2) NULL,
	`link_image` TEXT NULL,
	`image_position` FLOAT(8,2) NULL
)

;

CREATE TABLE `Job`
(
	`id_job` INT NOT NULL AUTO_INCREMENT,
	`data_no` VARCHAR(50) NULL,
	`customer` VARCHAR(50) NULL,
	`print_ref` VARCHAR(50) NULL,
	`project` VARCHAR(50) NULL,
	`qty` INT NULL,
	`supplier` VARCHAR(50) NULL,
	`c_order_date` DATE NULL,
	`po_sent` BOOL NULL,
	`approval_sent` BOOL NULL,
	`despatch_data` DATE NULL,
	`c_due_data` DATE NULL,
	`artwork_pre_approved` BOOL NULL,
	`c_artwork` VARCHAR(50) NULL,
	`c_artwork_visual` TEXT NULL,
	`c_approved_pdf` BOOL NULL,
	`c_approved_visual` BOOL NULL,
	`box_no` VARCHAR(50) NULL,
	`act_despatch_date` DATE NULL,
	`uk_tracking_no` INT NULL,
	`delivered_date` DATE NULL,
	`nett_sale` VARCHAR(50) NULL,
	`customer_reference_1` INT NULL,
	`s_ref` VARCHAR(50) NULL,
	`s_email` VARCHAR(50) NULL,
	`item` VARCHAR(50) NULL,
	`size` VARCHAR(50) NULL,
	`material` VARCHAR(50) NULL,
	`weight_thickness_capacity` VARCHAR(50) NULL,
	`print` VARCHAR(50) NULL,
	`coverage` VARCHAR(50) NULL,
	`print_style` VARCHAR(50) NULL,
	`finish_1` TEXT NULL,
	`finish_2` TEXT NULL,
	`finish_3` TEXT NULL,
	`service_level` VARCHAR(50) NULL,
	`status` VARCHAR(4) NULL,
	`notes` TEXT NULL,
	`note` TEXT NULL,
	`company_name` VARCHAR(50) NULL,
	`attn` VARCHAR(50) NULL,
	`tel` INT NULL,
	`email` VARCHAR(50) NULL,
	`delivery_address` VARCHAR(50) NULL,
	`uk_track_link` VARCHAR(50) NULL,
	`delivery_image` VARCHAR(50) NULL,
	`product_image` VARCHAR(50) NULL,
	`not_sure` VARCHAR(50) NULL,
	`pro_received` VARCHAR(50) NULL,
	CONSTRAINT `PK_Job` PRIMARY KEY (`id_job` ASC)
)

;

CREATE TABLE `Jobs`
(
	`id_jobs` INT NOT NULL,
	`name` VARCHAR(50) NULL,
	`description` TEXT NULL,
	`price_per_unit` FLOAT(0,0) NULL,
	`amount` INT NULL,
	`total` FLOAT(0,0) NULL,
	`link_pdf` TEXT NULL,
	`notes` TEXT NULL,
	`new_colour` BLOB NULL,
	`id_order` INT NULL,
	`id_extras` INT NULL,
	`id_clip` INT NULL,
	`id_price_amount` INT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_jobs` ASC)
)

;

CREATE TABLE `Orders`
(
	`id_order` INT NOT NULL,
	`data_time` DATETIME NULL,
	`shipping_days` INT NULL,
	`status` VARCHAR(50) NULL,
	`subtotal` FLOAT(7,3) NULL,
	`tax` FLOAT(7,3) NULL,
	`shipping_price` FLOAT(7,3) NULL,
	`total` FLOAT(7,3) NULL,
	`id_customer` INT NULL,
	`id_customers` INT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_order` ASC)
)

;

CREATE TABLE `Text`
(
	`id_jobs` INT NULL,
	`content_text` VARCHAR(50) NULL,
	`time_text` INT NULL,
	`space_between_text` FLOAT(8,2) NULL,
	`space_along_lanyard` FLOAT(8,2) NULL,
	`colour_text` VARCHAR(50) NULL,
	`font_family_text` VARCHAR(50) NULL,
	`size_text` FLOAT(8,2) NULL,
	`bold_text` BOOL NULL,
	`italic_text` BOOL NULL,
	`underline_text` BOOL NULL,
	`text_position` FLOAT(8,2) NULL
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Addresses` 
 ADD CONSTRAINT `FK_Addresses_Customers`
	FOREIGN KEY (`id_customers`) REFERENCES `Customers` (`id_customers`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Artwork` 
 ADD CONSTRAINT `FK_Artwork_Jobs`
	FOREIGN KEY (`id_jobs`) REFERENCES `Jobs` (`id_jobs`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Image` 
 ADD CONSTRAINT `FK_Image_Jobs`
	FOREIGN KEY (`id_jobs`) REFERENCES `Jobs` (`id_jobs`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Jobs` 
 ADD CONSTRAINT `FK_Jobs_Orders`
	FOREIGN KEY (`id_order`) REFERENCES `Orders` (`id_order`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Orders` 
 ADD CONSTRAINT `FK_Orders_Customers`
	FOREIGN KEY (`id_customers`) REFERENCES `Customers` (`id_customers`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Text` 
 ADD CONSTRAINT `FK_Text_Jobs`
	FOREIGN KEY (`id_jobs`) REFERENCES `Jobs` (`id_jobs`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
