INSERT INTO `product_category`

  (`code`, `name`) VALUES

('BAGS', 'Bags Category'),
('BADGES', 'Badges Category'),
('ACCESSOR', 'Clothing Accessories Category'),
('GADGETS', 'Gadgets Category'),
('LANYARDS', 'Lanyards and Accessories Category'),
('PACKAG', 'Packaging Category'),
('SAMPLES', 'Samples Picking Category'),
('SPECLPRJ', 'Special Projects Category'),
('CHRSTCAL', 'Calendars Category');


INSERT INTO `product_group`

(`code`, `name`, `prodcat`) VALUES

('NKA1CLA3', 'Classic Rope Handle Paper Bags', 'BAGS'),
('7A', 'Designer Luxury Rope Handle Paper Bags ', 'BAGS'),
('NKA1OVE3', 'Digital Twist Handle Paper Bags', 'BAGS'),
('NKA1GLOS', 'Gloss Twist Handle Bags ', 'BAGS'),
('7F', 'Spice Fabric Bags', 'BAGS'),
('NKA1BAGS', 'Uncoated Twist Handle Bags ', 'BAGS'),
('NKA1BUTT', ' Button Badges', 'BADGES'),
('NKA1SHOE', 'Shoe Laces ', 'ACCESSOR'),
('NKA1USBS', 'USB Sticks', 'GADGETS'),
('NKA1LAN1', 'Lanyard Card Holders Group', 'LANYARDS'),
('NKA1LANY', 'Lanyards', 'LANYARDS'),
('NKA1SAT1', 'Satin Ribbon', 'PACKAG'),
('NK', 'Kan samples', 'SAMPLES'),
('NKA1BESP	', ' works Hamble - Bespoke', 'SPECLPRJ'),
('NKA1CHOC', 'Chocolate Advent Calendars', 'CHRSTCAL');


INSERT INTO `product` (`id`, `name`, `code`, `size`, `material`, `weigth_thickness_capacity`, `print`, `coverage`, `print_style`, `finish1`, `finish2`, `finish3`) VALUES
('BCC10A10', ' Classic Copse Paper Bag - 350(w)+100(g)*250(h)(mm', 'NKA1CLA3','','','','','','','','',''),
('BCC10A1K', 'Classic Copse Paper Bag - 350(w)+100(g)*250(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC10A25', 'Classic Copse Paper Bag - 120(w)+100(g)*350(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC11A10', 'Classic Copse Paper Bag - 350(w)+100(g)*300(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC11A1K', ' Classic Copse Paper Bag - 350(w)+100(g)*300(h)(mm', 'NKA1CLA3','','','','','','','','',''),
('BCC11A25', 'Classic Copse Paper Bag - 350(w)+100(g)*300(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC12A10', 'Classic Copse Paper Bag - 350(w)+90(g)*420(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC12A1K', ' Classic Copse Paper Bag - 350(w)+90(g)*420(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC12A25', 'Classic Copse Paper Bag - 350(w)+90(g)*420(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC13A10', 'Classic Copse Paper Bag - 420(w)+100(g)*360(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC13A1K', 'Classic Copse Paper Bag - 420(w)+100(g)*360(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC13A25', 'Classic Copse Paper Bag - 420(w)+100(g)*360(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC1A100', 'Classic Copse Paper Bag - 120(w)+100(g)*350(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC1A11K', ' Classic Copse Paper Bag - 120(w)+100(g)*350(h)(mm', 'NKA1CLA3','','','','','','','','',''),
('BCC1A250', ' Classic Copse Paper Bag - 120(w)+100(g)*350(h)(mm', 'NKA1CLA3','','','','','','','','',''),
('BCC2A100', 'Classic Copse Paper Bag - 160(w)+80(g)*240(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC2A11K', 'Classic Copse Paper Bag - 160(w)+80(g)*240(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC2A250', 'Classic Copse Paper Bag - 160(w)+80(g)*240(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC3A100', ' Classic Copse Paper Bag - 200(w)+80(g)*200(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC3A11K', 'Classic Copse Paper Bag - 200(w)+80(g)*200(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC3A250', 'Classic Copse Paper Bag - 200(w)+80(g)*200(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC4A100', 'Classic Copse Paper Bag - 220(w)+90(g)*160(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC4A11K', 'Classic Copse Paper Bag - 220(w)+90(g)*160(h)(mm) ', 'NKA1CLA3','','','','','','','','',''),
('BCC4A250', 'Classic Copse Paper Bag - 220(w)+90(g)*160(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC5A100', 'Classic Copse Paper Bag - 230(w)+90(g)*220(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC5A11K', 'Classic Copse Paper Bag - 230(w)+90(g)*220(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC5A250', ' Classic Copse Paper Bag - 230(w)+90(g)*220(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC6A100', ' Classic Copse Paper Bag - 240(w)+90(g)*330(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC6A11K', 'Classic Copse Paper Bag - 240(w)+90(g)*330(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC6A250', 'Classic Copse Paper Bag - 240(w)+90(g)*330(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC7A100', 'Classic Copse Paper Bag - 240(w)+90(g)*380(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC7A11K', ' Classic Copse Paper Bag - 240(w)+90(g)*380(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC7A250', 'Classic Copse Paper Bag - 240(w)+90(g)*380(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC8A100', 'Classic Copse Paper Bag - 280(w)+100(g)*330(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC8A11K', 'Classic Copse Paper Bag - 280(w)+100(g)*330(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC8A250', 'Classic Copse Paper Bag - 280(w)+100(g)*330(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC9A100', ' Classic Copse Paper Bag - 320(w)+100(g)*420(h)(mm', 'NKA1CLA3','','','','','','','','',''),
('BCC9A11K', 'Classic Copse Paper Bag - 320(w)+100(g)*420(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('BCC9A250', ' Classic Copse Paper Bag - 320(w)+100(g)*420(h)(mm', 'NKA1CLA3','','','','','','','','',''),
('KA1BU16', 'Butterfly USB - 3x3', 'NKA1USBS','','','','','','','','',''),
('KNA1PEPP', 'Pepper Bag 1 Colour 2 Sides', '7F','','','','','','','','',''),
('NKA1120G', ' Uncoated Twist Handle Bag Small', 'NKA1BAGS','','','','','','','','',''),
('NKA1ADVE', 'Advent Calendar Milk Chocolate A4 ', 'NKA1CHOC','','','','','','','','',''),
('NKA1ASPE', 'Uncoated Twist Handle Bag Medium', 'NKA1BAGS','','','','','','','','',''),
('NKA1BU13', 'Butterfly USB - 2x0', 'NKA1USBS','','','','','','','','',''),
('NKA1BU14', 'Butterfly USB - 3x0', 'NKA1USBS','','','','','','','','',''),
('NKA1BU15', ' Butterfly USB - 4x0', 'NKA1USBS','','','','','','','','',''),
('NKA1BU17', 'Butterfly USB - 2x2', 'NKA1USBS','','','','','','','','',''),
('NKA1BU18', 'Butterfly USB - 4x4', 'NKA1USBS','','','','','','','','',''),
('NKA1BU19', ' Butterfly USB - 2x0 + Data Upload', 'NKA1USBS','','','','','','','','',''),
('NKA1BU20', 'Butterfly USB - 3x0 + Data Upload', 'NKA1USBS','','','','','','','','',''),
('NKA1BU21', 'Butterfly USB - 4x0 + Data Upload', 'NKA1USBS','','','','','','','','',''),
('NKA1BU22', 'Butterfly USB - 2x2 + Data Upload', 'NKA1USBS','','','','','','','','',''),
('NKA1BU23', 'Butterfly USB - 3x3 + Data Upload', 'NKA1USBS','','','','','','','','',''),
('NKA1BU24', ' Butterfly USB - 4x4 + Data Upload', 'NKA1USBS','','','','','','','','',''),
('NKA1BU26', 'Butterfly USB -1x1', 'NKA1USBS','','','','','','','','',''),
('NKA1BU27', 'Button Badge 32mm', 'NKA1BUTT','','','','','','','','',''),
('NKA1BU29', 'Button Badge 25mm', 'NKA1BUTT','','','','','','','','',''),
('NKA1BU30', 'Button Badge 25mm ', 'NKA1BUTT','','','','','','','','',''),
('NKA1BU33', 'Button Badge 32mm', 'NKA1BUTT','','','','','','','','',''),
('NKA1BU35', '16gb Butterfly USB - 4x0', 'NKA1USBS','','','','','','','','',''),
('NKA1BUT1', ' Button Badge 38mm', 'NKA1BUTT','','','','','','','','',''),
('NKA1BUT2', 'Button Badge 55mm', 'NKA1BUTT','','','','','','','','',''),
('NKA1BUT3', 'Button Badge 55mm', 'NKA1BUTT','','','','','','','','',''),
('NKA1BUT4', 'Button Badge 75mm', 'NKA1BUTT','','','','','','','','',''),
('NKA1BUT5', 'Button Badge 75mm', 'NKA1BUTT','','','','','','','','',''),
('NKA1BUT6', 'Butterfly USB -1x1 ', 'NKA1USBS','','','','','','','','',''),
('NKA1BUT7', 'Butterfly USB - 1x1 + Data Upload', 'NKA1USBS','','','','','','','','',''),
('NKA1BUTT', 'Button Badge 38mm', 'NKA1BUTT','','','','','','','','',''),
('NKA1CLA1', 'Classic Copse Paper Bag - 320(w)+100(g)*420(h)(mm)', 'NKA1CLA3','','','','','','','','',''),
('NKA1DDGB', ' DDG Bottle Bags', 'NKA1BESP	','','','','','','','','',''),
('NKA1DIGI', 'Digi Twist Handle Paper Bags 190 (100\'s) 1s', 'NKA1OVE3','','','','','','','','',''),
('NKA1EXPR', ' Gloss Twist Handle Bags Medium', 'NKA1GLOS','','','','','','','','',''),
('NKA1JUTE', 'Jute Bag Unprinted Sample 450+200x350mm', 'NKA1BESP	','','','','','','','','',''),
('NKA1LA10', 'Lanyard Rigid Card Holder Antimicrobial', 'NKA1LAN1','','','','','','','','',''),
('NKA1LA11', ' Lanyard Rigid Card Holder Antimicrobial', 'NKA1LAN1','','','','','','','','',''),
('NKA1LA12', 'Lanyard 15mm (10\'s) ', 'NKA1LANY','','','','','','','','',''),
('NKA1LA15', ' Lanyard 20mm', 'NKA1BESP	','','','','','','','','',''),
('NKA1LA16', 'Lanyard 25mm', 'NKA1BESP	','','','','','','','','',''),
('NKA1LA29', 'Lanyard 25mm (10\'s)', 'NKA1LANY','','','','','','','','',''),
('NKA1LA31', 'Lanyard 20mm (10\'s)', 'NKA1LANY','','','','','','','','',''),
('NKA1LA32', ' Lanyard 20mm (500\'s)', 'NKA1LANY','','','','','','','','',''),
('NKA1LA33', ' Lanyard 20mm (50\'s) ', 'NKA1LANY','','','','','','','','',''),
('NKA1LA35', 'Lanyard 20mm (50s)', 'NKA1LANY','','','','','','','','',''),
('NKA1LA39', ' Despatch label', 'NKA1BESP	','','','','','','','','',''),
('NKA1LAN1', ' Lanyard 15mm (500\'s)', 'NKA1LANY','','','','','','','','',''),
('NKA1LAN4', 'Lanyard 25mm (500\'s) ', 'NKA1LANY','','','','','','','','',''),
('NKA1LAN5', 'Lanyard 25mm (50\'s)', 'NKA1LANY','','','','','','','','',''),
('NKA1LAN6', 'Lanyard Soft Pouch Card Holder', 'NKA1LAN1','','','','','','','','',''),
('NKA1LAN7', 'Lanyard Soft Pouch Card Holder', 'NKA1LAN1','','','','','','','','',''),
('NKA1LAN8', ' Lanyard Rigid Card Holder Standard ', 'NKA1LAN1','','','','','','','','',''),
('NKA1LAN9', 'Lanyard Rigid Card Holder Standard', 'NKA1LAN1','','','','','','','','',''),
('NKA1LANY', ' Lanyard 15mm (50\'s) ', 'NKA1LANY','','','','','','','','',''),
('NKA1OVER', 'Digi Twist Handle Paper Bags 190 (1,000\'s) 1s', 'NKA1OVE3','','','','','','','','',''),
('NKA1PAP1', 'Uncoated Twist Handle Bag Medium', 'NKA1BAGS','','','','','','','','',''),
('NKA1PAP2', 'Gloss Twist Handle Bags Medium', 'NKA1GLOS','','','','','','','','',''),
('NKA1PAPE', 'Uncoated Twist Handle Bag Small', 'NKA1BAGS','','','','','','','','',''),
('NKA1PS74', 'Balsa Bags 1x0', 'NKA1BESP	','','','','','','','','',''),
('NKA1SA10', '25mm Satin Ribbon - 25m Roll', 'NKA1SAT1','','','','','','','','',''),
('NKA1SA11', '25mm Satin Ribbon - 25m Roll ', 'NKA1SAT1','','','','','','','','',''),
('NKA1SA12', '25mm Satin Ribbon - 50m Roll ', 'NKA1SAT1','','','','','','','','',''),
('NKA1SA13	', '25mm Satin Ribbon - 50m Roll', 'NKA1SAT1','','','','','','','','',''),
('NKA1SA14', ' 25mm Satin Ribbon - 100m Roll', 'NKA1SAT1','','','','','','','','',''),
('NKA1SA15', '25mm Satin Ribbon - 100m Roll', 'NKA1SAT1','','','','','','','','',''),
('NKA1SAT1', '15mm Satin Ribbon - 10m Roll', 'NKA1SAT1','','','','','','','','',''),
('NKA1SAT2	', ' 15mm Satin Ribbon - 25m Roll', 'NKA1SAT1','','','','','','','','',''),
('NKA1SAT3', ' 15mm Satin Ribbon - 25m Roll', 'NKA1SAT1','','','','','','','','',''),
('NKA1SAT4', '15mm Satin Ribbon - 50m Roll', 'NKA1SAT1','','','','','','','','',''),
('NKA1SAT5', ' 15mm Satin Ribbon - 50m Roll', 'NKA1SAT1','','','','','','','','',''),
('NKA1SAT6', '15mm Satin Ribbon - 100m Roll ', 'NKA1SAT1','','','','','','','','',''),
('NKA1SAT7', '15mm Satin Ribbon - 100m Roll', 'NKA1SAT1','','','','','','','','',''),
('NKA1SAT8', '25mm Satin Ribbon - 10m Roll', 'NKA1SAT1','','','','','','','','',''),
('NKA1SAT9', '25mm Satin Ribbon - 10m Roll ', 'NKA1SAT1','','','','','','','','',''),
('NKA1SATI', '15mm Satin Ribbon - 10m Roll', 'NKA1SAT1','','','','','','','','',''),
('NKA1SCRE', ' Screen Printed Lanyards 15mm (100s)', 'NKA1LANY','','','','','','','','',''),
('NKA1SHO1', 'Shoe Laces - Screen Printed', 'NKA1SHOE','','','','','','','','',''),
('NKA1SHO2', 'Shoe Laces - Full Colour', 'NKA1SHOE','','','','','','','','',''),
('NKA1SHO3', 'Shoe laces - Screen Printed', 'NKA1SHOE','','','','','','','','',''),
('NKA1SHO4', ' Shoelaces- Tubular Screen Printed', 'NKA1SHOE','','','','','','','','',''),
('NKA1SHO5', 'Shoelaces- Tubular Screen Printed S', 'NKA1SHOE','','','','','','','','',''),
('NKA1SHOE', 'Shoe Laces - Full Colour', 'NKA1SHOE','','','','','','','','',''),
('NKA1USB1', 'Butterfly USB -1x0', 'NKA1USBS','','','','','','','','',''),
('NKA1USBB', ' Butterfly USB - 1x0 + Data Upload', 'NKA1USBS','','','','','','','','',''),
('YKAGPB1', 'Lime Gloss Paper Bag - 1 Colour', '7A','','','','','','','','',''),
('YKAGPB2', 'Lime Gloss Paper Bag - 2 Colour', '7A','','','','','','','','',''),
('YKAGPB3', ' Lime Gloss Paper Bag - 3 Colour', '7A','','','','','','','','',''),
('YKAGPBF', 'Lime Gloss Paper Bag - Full Colour', '7A','','','','','','','','',''),
('YKAGPL1', 'Redwood Gloss Paper Bag - 1 Colour', '7A','','','','','','','','',''),
('YKAGPL2', 'Redwood Gloss Paper Bag - 2 Colour', '7A','','','','','','','','',''),
('YKAGPL3', 'Redwood Gloss Paper Bag - 3 Colour', '7A','','','','','','','','',''),
('YKAGPLF', 'Redwood Gloss Paper Bag - Full Colour', '7A','','','','','','','','',''),
('YKAGPM1', 'Oak Gloss Paper Bag - 1 Colour', '7A','','','','','','','','',''),
('YKAGPM2', 'Oak Gloss Paper Bag - 2 Colour', '7A','','','','','','','','',''),
('YKAGPM3', 'Oak Gloss Paper Bag - 3 Colour', '7A','','','','','','','','',''),
('YKAGPME1', ' Sycamore Gloss Paper Bag - 1 Colour ', '7A','','','','','','','','',''),
('YKAGPME2', 'Sycamore Gloss Paper Bag - 2 Colour', '7A','','','','','','','','',''),
('YKAGPME3', 'Sycamore Gloss Paper Bag - 3 Colour', '7A','','','','','','','','',''),
('YKAGPME4', ' Sycamore Gloss Paper Bag - Full Colour', '7A','','','','','','','','',''),
('YKAGPMF', ' Oak Gloss Paper Bag - Full Colour', '7A','','','','','','','','',''),
('YKAGPS1', 'Maple Gloss Paper Bag - 1 Colour', '7A','','','','','','','','',''),
('YKAGPS2', ' Maple Gloss Paper Bag - 2 Colour', '7A','','','','','','','','',''),
('YKAGPS3', ' Maple Gloss Paper Bag - 3 Colour', '7A','','','','','','','','',''),
('YKAGPSF', ' Maple Gloss Paper Bag - Full Colour', '7A','','','','','','','','',''),
('YKAGPX1', 'Birch Gloss Paper Bag - 1 Colour ', '7A','','','','','','','','',''),
('YKAGPX2', 'Birch Gloss Paper Bag - 2 Colour', '7A','','','','','','','','',''),
('YKAGPX3', 'Birch Gloss Paper Bag - 3 Colour', '7A','','','','','','','','',''),
('YKAGPXF', ' Birch Gloss Paper Bag - Full Colour', '7A','','','','','','','','',''),
('YKAMPB1', ' Lime Matt Paper Bag - 1 Colour', '7A','','','','','','','','',''),
('YKAMPB2', 'Lime Matt Paper Bag - 2 Colour', '7A','','','','','','','','',''),
('YKAMPB3', 'Lime Matt Paper Bag - 3 Colour', '7A','','','','','','','','',''),
('YKAMPBF', ' Lime Matt Paper Bag - Full Colour', '7A','','','','','','','','',''),
('YKAMPL1', 'Redwood Matt Paper Bag - 1 Colour ', '7A','','','','','','','','',''),
('YKAMPL2', 'Redwood Matt Paper Bag - 2 Colour', '7A','','','','','','','','',''),
('YKAMPL3', ' Redwood Matt Paper Bag - 3 Colour', '7A','','','','','','','','',''),
('YKAMPLF', ' Redwood Matt Paper Bag - Full Colour', '7A','','','','','','','','',''),
('YKAMPM1', 'Oak Matt Paper Bag - 1 Colour', '7A','','','','','','','','',''),
('YKAMPM2', ' Oak Matt Paper Bag - 2 Colour', '7A','','','','','','','','',''),
('YKAMPM3', ' Oak Matt Paper Bag - 3 Colour', '7A','','','','','','','','',''),
('YKAMPME1', ' Sycamore Matt Paper Bag - 1 Colour', '7A','','','','','','','','',''),
('YKAMPME2', 'Sycamore Matt Paper Bag - 2 Colour', '7A','','','','','','','','',''),
('YKAMPME3', ' Sycamore Matt Paper Bag - 3 Colour ', '7A','','','','','','','','',''),
('YKAMPME4', 'Sycamore Matt Paper Bag - Full Colour', '7A','','','','','','','','',''),
('YKAMPMF', 'Oak Matt Paper Bag - Full Colour', '7A','','','','','','','','',''),
('YKAMPS1', 'Maple Matt Paper Bag - 1 Colour', '7A','','','','','','','','',''),
('YKAMPS2', 'Maple Matt Paper Bag - 2 Colour', '7A','','','','','','','','',''),
('YKAMPS3', 'Maple Matt Paper Bag - 3 Colour', '7A','','','','','','','','',''),
('YKAMPSF', ' Maple Matt Paper Bag - Full Colour', '7A','','','','','','','','',''),
('YKAMPX1', 'Birch Matt Paper Bag - 1 Colour', '7A','','','','','','','','',''),
('YKAMPX2', 'Birch Matt Paper Bag - 2 Colour ', '7A','','','','','','','','',''),
('YKAMPX3', 'Birch Matt Paper Bag - 3 Colour', '7A','','','','','','','','',''),
('YKAMPXF', 'Birch Matt Paper Bag - Full Colour', '7A','','','','','','','','',''),
('YKAMPXF1', 'Birch Matt Paper Bag - Full Colour +1', '7A','','','','','','','','',''),
('YKAPEP11', 'Pepper Bag 1 Colour 1 Side', '7F','','','','','','','','',''),
('YKAPEP12', 'Pepper Bag 1 Colour 2 Sides', '7F','','','','','','','','',''),
('YKAPEP21', 'Pepper Bag 2 Colour 1 Side', '7F','','','','','','','','',''),
('YKAPEP22', 'Pepper Bag 2 Colour 2 Sides', '7F','','','','','','','','',''),
('YKAPEP31', ' Pepper Bag 3 Colour 1 Side', '7F','','','','','','','','',''),
('YKAPEP32', ' Pepper Bag 3 Colour 2 Sides', '7F','','','','','','','','',''),
('YKAPEP41', 'Pepper Bag 4 Colour 1 Side', '7F','','','','','','','','',''),
('YKAPEP42', 'Pepper Bag 4 Colour 2 Sides', '7F','','','','','','','','',''),
('YKASAMP1', ' Kan Ltd Bag Sample Pack ', 'NK','','','','','','','','','');


INSERT INTO `Users` (`idUser`, `name`, `email`, `password`, `images`, `userType`) VALUES
(2, 'Cat', 'Catrina@kan-do-it.com', '32skiff32', NULL, NULL),
(3, 'Ian', 'Ian@kan-do-it.com', '32skiff32', NULL, NULL),
(4, 'Aleja', 'alejandra.rozo@gmail.com', '123', NULL, 'Admin');
