/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 10-May-2023 7:04:32 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;
/* Drop Tables */

DROP TABLE IF EXISTS `Customer`
;

DROP TABLE IF EXISTS `Jobs`
;

DROP TABLE IF EXISTS `Order`
;

DROP TABLE IF EXISTS `prices`
;

DROP TABLE IF EXISTS `product`
;

DROP TABLE IF EXISTS `product_category`
;

DROP TABLE IF EXISTS `product_group`
;

DROP TABLE IF EXISTS `Suppliers`
;

DROP TABLE IF EXISTS `Users`
;

/* Create Tables */

CREATE TABLE `Customer`
(
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NULL,
	`address1` VARCHAR(50) NULL,
	`address2` VARCHAR(50) NULL,
	`address3` VARCHAR(50) NULL,
	`address4` VARCHAR(50) NULL,
	`address5` VARCHAR(50) NULL,
	`address6` VARCHAR(50) NULL,
	`postcode` VARCHAR(50) NULL,
	`countrycode` VARCHAR(50) NULL,
	`contact` VARCHAR(50) NULL,
	`telephone` VARCHAR(50) NULL,
	`email` VARCHAR(50) NULL,
	`best_name` VARCHAR(50) NULL,
	`country` VARCHAR(50) NULL,
	`despatch_method` VARCHAR(50) NULL,
	`despatch_method_name` VARCHAR(50) NULL,
	`despatch_customer_code` VARCHAR(50) NULL,
	`despatch_customer_address_id` VARCHAR(50) NULL,
	`line` VARCHAR(50) NULL,
	`main_contact_firstname` VARCHAR(50) NULL,
	`main_contact_surname` VARCHAR(50) NULL,
	`main_contact_title` VARCHAR(50) NULL,
	`main_contact_email` VARCHAR(50) NULL,
	`main_contact_telephone` VARCHAR(50) NULL,
	`invoice_contact_firstname` VARCHAR(50) NULL,
	`invoice_contact_surname` VARCHAR(50) NULL,
	`invoice_contact_title` VARCHAR(50) NULL,
	`invoice_contact_email` VARCHAR(50) NULL,
	`invoice_contact_telephone` VARCHAR(50) NULL,
	`vat_number` VARCHAR(50) NULL,
	CONSTRAINT `PK_Customer` PRIMARY KEY (`code` ASC)
)

;

CREATE TABLE `Jobs`
(
	`id` VARCHAR(50) NOT NULL,
	`status` VARCHAR(50) NULL,
	`customer` VARCHAR(50) NULL,
	`cotact` VARCHAR(50) NULL,
	`quantity_allocated` VARCHAR(50) NULL,
	`quantity_printed` VARCHAR(50) NULL,
	`quantity_despatched` VARCHAR(50) NULL,
	`total_transfer` VARCHAR(50) NULL,
	`total_selling` VARCHAR(50) NULL,
	`total` VARCHAR(50) NULL,
	`client_reference` VARCHAR(50) NULL,
	`total_prcost` VARCHAR(50) NULL,
	`title` VARCHAR(50) NULL,
	`category` VARCHAR(50) NULL,
	`quantity` VARCHAR(50) NULL,
	`auto081` VARCHAR(50) NULL,
	`service` VARCHAR(50) NULL,
	`supplier_reference` VARCHAR(50) NULL,
	`reprintof` VARCHAR(50) NULL,
	`reprintas` VARCHAR(50) NULL,
	`reorderof` VARCHAR(50) NULL,
	`reorderas` VARCHAR(50) NULL,
	`product_name` VARCHAR(50) NULL,
	`spec` VARCHAR(50) NULL,
	`turnaround` VARCHAR(50) NULL,
	`schedule` VARCHAR(50) NULL,
	`weight` VARCHAR(50) NULL,
	`status_text` VARCHAR(50) NULL,
	`status_note` VARCHAR(50) NULL,
	`height` VARCHAR(50) NULL,
	`width` VARCHAR(50) NULL,
	`bleed` VARCHAR(50) NULL,
	`reseller_details` VARCHAR(50) NULL,
	`product_spec` VARCHAR(50) NULL,
	`product_design` VARCHAR(50) NULL,
	`product_special` VARCHAR(50) NULL,
	`product_partner_code` VARCHAR(50) NULL,
	`prod_workgroup` VARCHAR(50) NULL,
	`complete` VARCHAR(50) NULL,
	`multifile` VARCHAR(50) NULL,
	`expected_despatch_date` VARCHAR(50) NULL,
	`front_filename` VARCHAR(50) NULL,
	`reverse_filename` VARCHAR(50) NULL,
	`fee_charged_on_job` VARCHAR(50) NULL,
	`pages` VARCHAR(50) NULL,
	`despatches` VARCHAR(50) NULL,
	`revenue` VARCHAR(50) NULL,
	`notes` VARCHAR(50) NULL,
	`finishes` VARCHAR(50) NULL,
	`orientation` VARCHAR(50) NULL,
	`order_code` VARCHAR(50) NULL,
	`package_code` VARCHAR(50) NULL,
	`jobmaker_pack` VARCHAR(50) NULL,
	`file_paths` VARCHAR(50) NULL,
	`data_no` VARCHAR(50) NULL,
	`print_ref` VARCHAR(50) NULL,
	`project` VARCHAR(50) NULL,
	`PO_sent` DATE NULL,
	`approval_sent` DATE NULL,
	`C_due_date` DATE NULL,
	`artwork_pre_approved` INT NULL,
	`C_artwork` VARCHAR(50) NULL,
	`C_artwork_visual` VARCHAR(50) NULL,
	`C_approved_PDF` VARCHAR(50) NULL,
	`C_approved_visual` VARCHAR(50) NULL,
	`box_no` VARCHAR(50) NULL,
	`act_despatch_date` DATE NULL,
	`UK_tracking_no` VARCHAR(50) NULL,
	`delivered_date` DATE NULL,
	`nett_sale` VARCHAR(50) NULL,
	`service_level` VARCHAR(50) NULL,
	`status_order` VARCHAR(50) NULL,
	`note` VARCHAR(50) NULL,
	`UK_track_link` VARCHAR(50) NULL,
	`delivery_image` VARCHAR(50) NULL,
	`not_sure` VARCHAR(50) NULL,
	`PO_received` DATE NULL,
	`addresses` VARCHAR(50) NULL,
	`reseller_workgroup` INT NULL,
	`product_code` VARCHAR(50) NULL,
	`idUser` INT NULL,
	`idOrder` VARCHAR(50) NULL,
	CONSTRAINT `PK_Jobs` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Order`
(
	`id` VARCHAR(50) NOT NULL,
	`created_date` DATE NULL,
	`name` VARCHAR(50) NULL,
	`runtype` VARCHAR(50) NULL,
	`description` VARCHAR(50) NULL,
	`finished_date` DATE NULL,
	`workgroup` VARCHAR(50) NULL,
	CONSTRAINT `PK_Order` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `prices`
(
	`id` VARCHAR(50) NOT NULL,
	`selling` VARCHAR(50) NULL,
	`transfer` VARCHAR(50) NULL,
	`production` VARCHAR(50) NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `product`
(
	`id` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NULL,
	`code` VARCHAR(50) NULL,
	`size` VARCHAR(50) NULL,
	`material` VARCHAR(50) NULL,
	`weigth_thickness_capacity` VARCHAR(50) NULL,
	`print` VARCHAR(50) NULL,
	`coverage` VARCHAR(50) NULL,
	`print_style` VARCHAR(50) NULL,
	`finish1` VARCHAR(50) NULL,
	`finish2` VARCHAR(50) NULL,
	`finish3` VARCHAR(50) NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `product_category`
(
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NULL,
	CONSTRAINT `PK_product_category` PRIMARY KEY (`code` ASC)
)

;

CREATE TABLE `product_group`
(
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NULL,
	`prodcat` VARCHAR(50) NULL,
	CONSTRAINT `PK_product_group` PRIMARY KEY (`code` ASC)
)

;

CREATE TABLE `Suppliers`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL,
	`email` VARCHAR(50) NULL,
	CONSTRAINT `PK_Suppliers` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Users`
(
	`idUser` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL,
	`email` VARCHAR(50) NULL,
	`company` VARCHAR(50) NULL,
	`tel` VARCHAR(50) NULL,
	`password` VARCHAR(50) NULL,
	`images` TEXT NULL,
	`userType` VARCHAR(50) NULL,
	CONSTRAINT `PK_Users` PRIMARY KEY (`idUser` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Jobs`
 ADD INDEX `IXFK_Jobs_Customer` (`addresses` ASC)
;

ALTER TABLE `Jobs`
 ADD INDEX `IXFK_Jobs_Order` (`idOrder` ASC)
;

ALTER TABLE `Jobs`
 ADD INDEX `IXFK_Jobs_Suppliers` (`reseller_workgroup` ASC)
;

ALTER TABLE `Jobs`
 ADD INDEX `IXFK_Jobs_Users` (`idUser` ASC)
;

ALTER TABLE `product`
 ADD INDEX `IXFK_product_product_group` (`code` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `Jobs`
 ADD CONSTRAINT `FK_Jobs_Customer`
	FOREIGN KEY (`addresses`) REFERENCES `Customer` (`code`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Jobs`
 ADD CONSTRAINT `FK_Jobs_Order`
	FOREIGN KEY (`idOrder`) REFERENCES `Order` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Jobs`
 ADD CONSTRAINT `FK_Jobs_product`
	FOREIGN KEY (`product_code`) REFERENCES `product` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Jobs`
 ADD CONSTRAINT `FK_Jobs_Suppliers`
	FOREIGN KEY (`reseller_workgroup`) REFERENCES `Suppliers` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Jobs`
 ADD CONSTRAINT `FK_Jobs_Users`
	FOREIGN KEY (`idUser`) REFERENCES `Users` (`idUser`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `prices`
 ADD CONSTRAINT `FK_prices_product`
	FOREIGN KEY (`id`) REFERENCES `product` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `product`
 ADD CONSTRAINT `FK_product_product_group`
	FOREIGN KEY (`code`) REFERENCES `product_group` (`code`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `product_group`
 ADD CONSTRAINT `FK_product_group_product_category`
	FOREIGN KEY (`prodcat`) REFERENCES `product_category` (`code`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;
